"""create all tables

Revision ID: 34400b19be4a
Revises: 
Create Date: 2022-06-14 09:21:05.941182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34400b19be4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('meanscore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=64), nullable=True),
    sa.Column('math', sa.Integer(), nullable=True),
    sa.Column('english', sa.Integer(), nullable=True),
    sa.Column('science', sa.Integer(), nullable=True),
    sa.Column('ict', sa.Integer(), nullable=True),
    sa.Column('history', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meanscore')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
